services:
  # Defines a service name
  workspace:
    build:
      # Sets the build context to the current directory
      context: .
      # Specifies the Dockerfile to use for the build
      dockerfile: .docker/Dockerfile.dev
      # Specifies build-time variables (ARGs)
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $CONTAINER_USERNAME
        ARG_USER_UID: $CONTAINER_USER_UID
        ARG_USER_GID: $CONTAINER_USER_GID
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_DIRNAME: $APP_DIRNAME
        ARG_CONTAINER_SERVICE_NAME: $CONTAINER_SERVICE_NAME
        TRT_VER: "10.3.0.26"
        CUDA_VER: "12.5"
        CUDNN_VER: "9.2.1.18-1"
        NCCL_VER: "2.22.3-1+cuda12.5"
        CUBLAS_VER: "12.5.3.2-1"
        NVRTC_VER: "12.5.82-1"
        TORCH_INSTALL_TYPE: "skip"
        TRT_GIT_COMMIT: $TRT_GIT_COMMIT
        TRT_LLM_VERSION: $TRT_LLM_VERSION
    # Sets the image name for the built image
    image: $IMAGE_NAME:$IMAGE_TAG
    # Sets the hostname of the container
    hostname: $CONTAINER_HOSTNAME
    # Sets tty to true if the container needs a pseudo-TTY
    tty: false
    command:
      # Specifies the command to be executed when the container is run
      - bash
      - $CONTAINER_LAUNCH_SCRIPT
    # set the environment variables
    environment:
      USER_UID: $CONTAINER_USER_UID
      USER_GID: $CONTAINER_USER_GID
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
      IMAGE_VARIANT: $IMAGE_VARIANT
    ulimits:
      # Sets the stack size and memory lock limits
      stack: 67108864
      memlock: -1
    # Allows the container to use the host's IPC namespace
    ipc: $CONTAINER_IPC
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_SSH_PORT:$CONTAINER_SSH_PORT"
      - "$HOST_WEB_SVC_PORT:$CONTAINER_WEB_SVC_PORT"
    volumes:
      # Maps directories from the host to the container
      - "$HOST_SCRIPTS_DIR:$CONTAINER_WORKSPACE_ROOT/scripts"
      - "$HOST_HF_HOME:$CONTAINER_HF_HOME"
    deploy:
      resources:
        reservations:
          devices:
            # Reserves the specified GPU for the container
            - driver: nvidia
              device_ids: ["${CONTAINER_CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $CONTAINER_NETWORK_NAME
    external: true
